# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
from functools import partial

from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtCore import pyqtSignal
from PyQt6.QtGui import QFontDatabase, QFont

from src.DataLoader.dataDishesLoader import SortDishes


class Left_settings_panel(QtWidgets.QWidget):
    data_updated = QtCore.pyqtSignal(list)

    def __init__(self, parent=None):
        super().__init__(parent)

        # gets information about dishes from the sortDishes() class from dataDishesLoader.py
        self.sorter = SortDishes()

        antonF = QFontDatabase.addApplicationFont("../src/assets/font/Anton-Regular.ttf")
        antonFont = QFontDatabase.applicationFontFamilies(antonF)

        self.mainLayout = QtWidgets.QVBoxLayout()
        self.mainLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMaximumSize)
        self.mainLayout.setContentsMargins(0, 0, 0, 0)
        self.mainLayout.setSpacing(0)

        self.frame_main = QtWidgets.QFrame()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_main.sizePolicy().hasHeightForWidth())
        self.frame_main.setSizePolicy(sizePolicy)
        self.frame_main.setStyleSheet("background-color:#21252F;")
        self.frame_main.setMinimumSize(QtCore.QSize(290, 0))
        self.frame_main.setMaximumSize(QtCore.QSize(290, 10000))
        self.frame_main.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_main.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)

        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setContentsMargins(8, 16, 8, 16)
        self.verticalLayout_13.setSpacing(32)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.app_logo = QtWidgets.QLabel()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)

        sizePolicy.setHeightForWidth(self.app_logo.sizePolicy().hasHeightForWidth())

        # ---- application logo ----
        self.app_logo.setSizePolicy(sizePolicy)
        self.app_logo.setMinimumSize(QtCore.QSize(0, 0))
        self.app_logo.setMaximumSize(QtCore.QSize(134, 80))
        self.app_logo.setBaseSize(QtCore.QSize(630, 100))
        self.app_logo.setText("")
        self.app_logo.setPixmap(QtGui.QPixmap("../src/assets/img.png"))
        self.app_logo.setScaledContents(True)
        self.app_logo.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.app_logo)

        self.verticalLayout_13.addLayout(self.horizontalLayout_5)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMaximumSize)
        self.verticalLayout_7.setSpacing(16)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMaximumSize)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")

        # ---- Settings name Label ----
        self.settings_label = QtWidgets.QLabel()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHeightForWidth(self.settings_label.sizePolicy().hasHeightForWidth())
        self.settings_label.setSizePolicy(sizePolicy)
        self.settings_label.setMinimumSize(QtCore.QSize(47, 0))
        self.settings_label.setFont(QFont(antonFont[0], 20))
        self.settings_label.setStyleSheet("color: white;")
        self.settings_label.setScaledContents(False)
        self.verticalLayout.addWidget(self.settings_label)

        self.line = QtWidgets.QFrame()
        self.line.setStyleSheet("background-color: #3D4358;")
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setLineWidth(4)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)

        self.verticalLayout.addWidget(self.line)
        self.verticalLayout_7.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMaximumSize)
        self.verticalLayout_3.setSpacing(2)

        # ---- label name "Dupe population" ----
        self.pop_label = QtWidgets.QLabel()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHeightForWidth(self.pop_label.sizePolicy().hasHeightForWidth())
        self.pop_label.setSizePolicy(sizePolicy)
        self.pop_label.setMinimumSize(QtCore.QSize(47, 0))
        self.pop_label.setFont(QFont(antonFont[0], 14))
        self.pop_label.setStyleSheet("color: white;")
        self.pop_label.setScaledContents(False)
        self.verticalLayout_3.addWidget(self.pop_label)

        # ---- Dupe population input frame ----
        self.frame = QtWidgets.QFrame()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setStyleSheet("background-color: #585C70;\n"
"border: 2px solid black;\n"
"border-radius: 4px;")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setLineWidth(1)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(8, 4, 8, 4)
        self.verticalLayout_2.setSpacing(0)

        # ---- Input variable name ----

        self.quantity_DP_input = QtWidgets.QSpinBox(parent=self.frame)
        self.quantity_DP_input.setFont(QFont(antonFont[0], 16))
        self.quantity_DP_input.setStyleSheet("border: none;\n"
"color: white;\n"
"text-size: 16px;")
        self.quantity_DP_input.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.verticalLayout_2.addWidget(self.quantity_DP_input)

        self.verticalLayout_3.addWidget(self.frame)
        self.verticalLayout_7.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMinimumSize)
        self.verticalLayout_4.setSpacing(2)

        # ---- label name "bottomless stomach" ----

        self.stomach_label = QtWidgets.QLabel()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stomach_label.sizePolicy().hasHeightForWidth())
        self.stomach_label.setSizePolicy(sizePolicy)
        self.stomach_label.setMinimumSize(QtCore.QSize(47, 0))
        self.stomach_label.setFont(QFont(antonFont[0], 14))
        self.stomach_label.setStyleSheet("color: white;")
        self.stomach_label.setScaledContents(False)
        self.verticalLayout_4.addWidget(self.stomach_label)

        # ---- Dupe population input frame ----

        self.frame_2 = QtWidgets.QFrame()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setStyleSheet("background-color: #585C70;\n"
"border: 2px solid black;\n"
"border-radius: 4px;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setLineWidth(1)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_5.setContentsMargins(8, 4, 8, 4)
        self.verticalLayout_5.setSpacing(0)

        # ---- Input variable name ----

        self.val_BS_input = QtWidgets.QSpinBox(parent=self.frame_2)
        self.val_BS_input.setFont(QFont(antonFont[0], 16))
        self.val_BS_input.setStyleSheet("border: none;\n"
"color: white;\n"
"text-size: 16px;")
        self.val_BS_input.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.verticalLayout_5.addWidget(self.val_BS_input)


        self.verticalLayout_4.addWidget(self.frame_2)
        self.verticalLayout_7.addLayout(self.verticalLayout_4)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMinimumSize)
        self.verticalLayout_6.setSpacing(2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")


        self.label_5 = QtWidgets.QLabel()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(47, 0))
        self.label_5.setFont(QFont(antonFont[0], 14))
        self.label_5.setStyleSheet("color: white;")
        self.label_5.setScaledContents(False)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_6.addWidget(self.label_5)

        # ---- difficulty combobox ----
        self.comboBox = QtWidgets.QComboBox()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setMinimumSize(QtCore.QSize(0, 0))
        self.comboBox.setMaximumSize(QtCore.QSize(16777215, 42))
        self.comboBox.setBaseSize(QtCore.QSize(0, 42))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("color: white;\n"
"background-color: #3D4358;\n"
"border: 2px solid black;\n"
"border-radius: 4px;\n"
"padding: 8px;")
        self.comboBox.setInsertPolicy(QtWidgets.QComboBox.InsertPolicy.InsertAtTop)
        self.comboBox.setFrame(False)
        self.comboBox.setFont(QFont(antonFont[0], 20))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout_6.addWidget(self.comboBox)
        self.verticalLayout_7.addLayout(self.verticalLayout_6)
        self.verticalLayout_13.addLayout(self.verticalLayout_7)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMinimumSize)
        self.verticalLayout_12.setSpacing(8)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMaximumSize)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_6 = QtWidgets.QLabel()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(47, 0))
        self.label_6.setFont(QFont(antonFont[0], 20))
        self.label_6.setStyleSheet("color: white;")
        self.label_6.setScaledContents(False)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_8.addWidget(self.label_6)
        self.line_2 = QtWidgets.QFrame()
        self.line_2.setStyleSheet("background-color: #3D4358;")
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_2.setLineWidth(4)
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_8.addWidget(self.line_2)
        self.verticalLayout_12.addLayout(self.verticalLayout_8)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMaximumSize)
        self.horizontalLayout_4.setSpacing(8)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMaximumSize)
        self.horizontalLayout.setObjectName("horizontalLayout")

        # ---- DLC button "Space Out" ----

        self.btn_dlc_SO = QtWidgets.QToolButton()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHeightForWidth(self.btn_dlc_SO.sizePolicy().hasHeightForWidth())
        self.btn_dlc_SO.setSizePolicy(sizePolicy)
        self.btn_dlc_SO.setStyleSheet("border:none;")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../src/assets/btn/dlc/btnImgSO.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon.addPixmap(QtGui.QPixmap("../src/assets/btn/dlc/btnImgSOClicked.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        icon.addPixmap(QtGui.QPixmap("../src/assets/btn/imgSOBtn.png"), QtGui.QIcon.Mode.Selected, QtGui.QIcon.State.Off)
        icon.addPixmap(QtGui.QPixmap("../src/assets/btn/imgSOBtnClicked.png"), QtGui.QIcon.Mode.Selected, QtGui.QIcon.State.On)
        self.btn_dlc_SO.setIcon(icon)
        self.btn_dlc_SO.setIconSize(QtCore.QSize(45, 42))
        self.btn_dlc_SO.setCheckable(True)
        self.btn_dlc_SO.setChecked(False)
        self.btn_dlc_SO.setObjectName("toolButton")

        # click emit
        self.btn_dlc_SO.toggled.connect(lambda checked, btn=self.btn_dlc_SO, dlc="Space Out": self.selectedDLC(btn, dlc))

        self.horizontalLayout.addWidget(self.btn_dlc_SO)
        self.verticalLayout_9.addLayout(self.horizontalLayout)

        # ---- DLC label name "Space Out" ----

        self.label_dlc_SO = QtWidgets.QLabel()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHeightForWidth(self.label_dlc_SO.sizePolicy().hasHeightForWidth())
        self.label_dlc_SO.setSizePolicy(sizePolicy)
        self.label_dlc_SO.setMinimumSize(QtCore.QSize(47, 0))
        self.label_dlc_SO.setFont(QFont(antonFont[0], 12))
        self.label_dlc_SO.setStyleSheet("color: white;")
        self.label_dlc_SO.setScaledContents(False)
        self.label_dlc_SO.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_dlc_SO.setObjectName("label_7")
        self.verticalLayout_9.addWidget(self.label_dlc_SO)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_9.addItem(spacerItem)
        self.horizontalLayout_4.addLayout(self.verticalLayout_9)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMaximumSize)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")

        # ---- DLC button "Prehistoric Planet Pack" ----

        self.btn_dlc_PPP = QtWidgets.QToolButton()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHeightForWidth(self.btn_dlc_PPP.sizePolicy().hasHeightForWidth())
        self.btn_dlc_PPP.setSizePolicy(sizePolicy)
        self.btn_dlc_PPP.setStyleSheet("border: none;")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../src/assets/btn/dlc/btnImgPPP.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon1.addPixmap(QtGui.QPixmap("../src/assets/btn/dlc/btnImgPPPClicked.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        icon1.addPixmap(QtGui.QPixmap("../src/assets/btn/dlc/btnImgPPP.png"), QtGui.QIcon.Mode.Selected, QtGui.QIcon.State.Off)
        icon1.addPixmap(QtGui.QPixmap("../src/assets/btn/dlc/btnImgPPPClicked.png"), QtGui.QIcon.Mode.Selected, QtGui.QIcon.State.On)
        self.btn_dlc_PPP.setIcon(icon1)
        self.btn_dlc_PPP.setIconSize(QtCore.QSize(45, 42))
        self.btn_dlc_PPP.setCheckable(True)
        self.btn_dlc_PPP.setChecked(False)
        self.btn_dlc_PPP.setObjectName("toolButton_2")

        # click emit
        self.btn_dlc_PPP.toggled.connect(lambda checked, btn=self.btn_dlc_PPP, dlc="Prehistoric Planet Pack": self.selectedDLC(btn, dlc))

        self.horizontalLayout_2.addWidget(self.btn_dlc_PPP)
        self.verticalLayout_10.addLayout(self.horizontalLayout_2)

        # ---- DLC label name "Prehistoric Planet Pack" ----

        self.label_dlc_PPP = QtWidgets.QLabel()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHeightForWidth(self.label_dlc_PPP.sizePolicy().hasHeightForWidth())
        self.label_dlc_PPP.setSizePolicy(sizePolicy)
        self.label_dlc_PPP.setMinimumSize(QtCore.QSize(47, 0))
        self.label_dlc_PPP.setFont(QFont(antonFont[0], 12))
        self.label_dlc_PPP.setStyleSheet("color: white;")
        self.label_dlc_PPP.setScaledContents(False)
        self.label_dlc_PPP.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.verticalLayout_10.addWidget(self.label_dlc_PPP)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_10.addItem(spacerItem1)

        self.horizontalLayout_4.addLayout(self.verticalLayout_10)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMaximumSize)

        # ---- DLC button "Frosty Planet Pack" ----

        self.btn_dlc_FPP = QtWidgets.QToolButton()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHeightForWidth(self.btn_dlc_FPP.sizePolicy().hasHeightForWidth())
        self.btn_dlc_FPP.setSizePolicy(sizePolicy)
        self.btn_dlc_FPP.setStyleSheet("border: none;")
        self.btn_dlc_FPP.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../src/assets/btn/dlc/btnImgFPP.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon2.addPixmap(QtGui.QPixmap("../src/assets/btn/dlc/btnImgFPPClicked.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        icon2.addPixmap(QtGui.QPixmap("../src/assets/btn/dlc/btnImgFPP.png"), QtGui.QIcon.Mode.Selected, QtGui.QIcon.State.Off)
        icon2.addPixmap(QtGui.QPixmap("../src/assets/btn/dlc/btnImgFPPClicked.png"), QtGui.QIcon.Mode.Selected, QtGui.QIcon.State.On)
        self.btn_dlc_FPP.setIcon(icon2)
        self.btn_dlc_FPP.setIconSize(QtCore.QSize(45, 42))
        self.btn_dlc_FPP.setCheckable(True)
        self.btn_dlc_FPP.setChecked(False)

        # click emit
        self.btn_dlc_FPP.toggled.connect(lambda checked, btn=self.btn_dlc_FPP, dlc="Frosty Planet Pack": self.selectedDLC(btn, dlc))

        self.horizontalLayout_3.addWidget(self.btn_dlc_FPP)
        self.verticalLayout_11.addLayout(self.horizontalLayout_3)

        # ---- DLC label name "Frosty Planet Pack" ----

        self.label_dlc_FPP = QtWidgets.QLabel()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHeightForWidth(self.label_dlc_FPP.sizePolicy().hasHeightForWidth())
        self.label_dlc_FPP.setSizePolicy(sizePolicy)
        self.label_dlc_FPP.setMinimumSize(QtCore.QSize(47, 0))
        self.label_dlc_FPP.setFont(QFont(antonFont[0], 12))
        self.label_dlc_FPP.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.label_dlc_FPP.setStyleSheet("color: white;")
        self.label_dlc_FPP.setScaledContents(False)
        self.label_dlc_FPP.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.verticalLayout_11.addWidget(self.label_dlc_FPP)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_11.addItem(spacerItem2)
        self.horizontalLayout_4.addLayout(self.verticalLayout_11)

        self.verticalLayout_12.addLayout(self.horizontalLayout_4)
        self.verticalLayout_13.addLayout(self.verticalLayout_12)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_13.addItem(spacerItem3)

        self.frame_main.setLayout(self.verticalLayout_13)
        self.mainLayout.addWidget(self.frame_main)
        self.setLayout(self.mainLayout)

        self.retranslateUi()
        self.comboBox.setCurrentIndex(2)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.settings_label.setText(_translate("Form", "Settings"))
        self.pop_label.setText(_translate("Form", "Dupe population"))
        self.stomach_label.setText(_translate("Form", "bottomless stomach"))
        self.label_5.setText(_translate("Form", "Settings"))
        self.comboBox.setItemText(0, _translate("Form", "Tummyless"))
        self.comboBox.setItemText(1, _translate("Form", "Fasting"))
        self.comboBox.setItemText(2, _translate("Form", "Default"))
        self.comboBox.setItemText(3, _translate("Form", "Rumbly Tummies"))
        self.comboBox.setItemText(4, _translate("Form", "Ravenous"))
        self.label_6.setText(_translate("Form", "Settings"))
        self.label_dlc_SO.setText(_translate("Form", "Space out!"))
        self.label_dlc_PPP.setText(_translate("Form", "Prehistoric\n"
"Planet Pack"))
        self.label_dlc_FPP.setText(_translate("Form", "Frosty planet pack"))

    def selectedDLC(self, btn, dlc):


        if btn.isChecked():
            if dlc not in self.sorter.selected_dlcs:
                self.sorter.selected_dlcs.append(dlc)
        else:
            if dlc in self.sorter.selected_dlcs:
                self.sorter.selected_dlcs.remove(dlc)

        data = self.sorter.sort_by_dlc()
        # emitujemy najnowsze filtrowane dane
        self.data_updated.emit(data)
